#!/bin/bash

# Use to update JMeter compatibility layer.
# Run in package root to produce file/jmeter-compat.js with latest versions.
# Commit the new bundle to save.
# Install browserify before use: npm install --global browserify

rm -rf build
mkdir -p build
cd build
echo '{"name":"-","version":"-"}' >package.json
echo "module.exports = {
    buffer: require('buffer'),
    he: require('he'),
    iconv: require('iconv-lite'),
    jsonpath: require('jsonpath'),
    papaparse: require('papaparse'),
    perlRegex: require('perl-regex'),
    yaml: require('yaml')
}" >package.js
npm install buffer he iconv-lite jsonpath papaparse perl-regex \
    @babel/runtime yaml
browserify package.js -s jmeterCompat > ../file/jmeter-compat.js
