#!/bin/bash

mkdir -p build
cd build
echo '{"name":"-","version":"-"}' >package.json

# buffer
npm install buffer
echo "module.exports = require('buffer/')" >index.js
browserify index.js -s buffer >buffer.js

# he
npm install he
echo "module.exports = require('he')" >index.js
browserify index.js -s he >he.js

# iconv-lite
npm install iconv-lite
echo "module.exports = require('iconv-lite')" >index.js
browserify index.js -s iconv >iconv.js

# jsonpath
npm install jsonpath
echo "module.exports = require('jsonpath')" >index.js
browserify index.js -s jsonpath >jsonpath.js

# papaparse
npm install papaparse
echo "module.exports = require('papaparse')" >index.js
browserify index.js -s papaparse >papaparse.js

# perl-regex
npm install perl-regex
echo "module.exports = require('perl-regex')" >index.js
browserify index.js -s perl-regex >perl-regex.js

# yaml
npm install yaml
echo "module.exports = require('yaml')" >index.js
browserify index.js -s yaml >yaml.js
